name: Build and publish release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: release-env

    steps:
    - uses: actions/checkout@v3
      with:
        ref: "main"
    - name: Get release version from tag
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Bump version
      run: |
        echo "foo " >> README.md 
    - name: Commit version.txt
      run: |
        git config --global user.name 'release-bot'
        git config --global user.email 'release-bot@users.noreply.github.com'
        git add README.md
        git commit -m "Release v${{ env.RELEASE_VERSION }}"
        git push
