name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:

  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description:  Please describe what the bug is and what you expected to happen.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: If possible, please provide a script that can reproduce the issue.

  - type: dropdown
    id: feature
    attributes:
      label: Feature
      description: What area of DeepSpeed does this bug relate to?
      options:
        - Training
        - Inference
        - Compression
        - Other
    validations:
      required: true
